In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("dataset/LMS_Dirty_Dataset.csv")
# dataset exploration
# data.head(10)
# data.tail(10)
# data.shape
# data.columns
# data.dtypes
# data.describe()

In [3]:
data.duplicated().sum()
data["student_id"].duplicated().sum()

0

In [4]:
data.isnull().sum()
data["attendance_percent"].isnull()
data["attendance_percent"]=pd.to_numeric(data["attendance_percent"])
data["attendance_percent"]=data["attendance_percent"].fillna(data["attendance_percent"].median())
data.loc[25:35, ["attendance_percent"]]

    attendance_percent
25                95.0
26                78.0
27                98.0
28                70.0
29                64.0
30                83.0
31                62.0
32                64.0
33                41.0
34                48.0
35                94.0

In [5]:
data.dtypes
data["enrollment_date"]=pd.to_datetime(data["enrollment_date"])
data.dtypes

student_id                     int64
student_name                  object
course                        object
city                          object
age                            int64
gender                        object
enrollment_date       datetime64[ns]
course_fee                     int64
discount                     float64
payment_status                object
attendance_percent           float64
assignment_score               int64
final_score                    int64
rating                         int64
mentor                        object
phone                         object
email                         object
completion_status             object
dtype: object

In [25]:
data["city"]=data["city"].str.title().str.strip()
data["course"]=data["course"].str.title().str.strip()
data["payment_status"] = data["payment_status"].str.title().str.strip()
data["completion_status"] = data["completion_status"].str.title().str.strip()
data

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,Mern Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,Mern Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,346,Hari,Ui/Ux,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,Ui/Ux,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed
349,350,Hari,Python With Ai/Ml,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,user349@gmail.com,Ongoing

In [31]:
data[data["course_fee"]<0]
data.loc[data["course_fee"]<0,"course_fee"]=0
data["course_fee"]=data["course_fee"].fillna(data["course_fee"])
data[data["rating"]<0]

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status]
Index: []

In [6]:
# course_fee
Q1=data["course_fee"].quantile(0.25)
print(Q1)
Q3=data["course_fee"].quantile(0.75)
print(Q3)
IQR=Q3-Q1
print(IQR)

lower_fee=Q1-1.5*IQR
print(lower_fee)
upper_fee=Q3+1.5*IQR
print(upper_fee)

outlier_fee=data[(data["course_fee"]<lower_fee)|(data["course_fee"]>upper_fee)]
outlier_fee

134.5
134.5
0.0
134.5
134.5

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
8,9,Gita,Flutter,Biratnagar,31,Male,2026-05-06,0.0,10.0,Pending,70.0,88,98,4,Ishan,9869507556,user8@gmail.com,Completed

In [33]:
#attendence_percnetage
Q1=data["attendance_percent"].quantile(0.25)
print(Q1)
Q3=data["attendance_percent"].quantile(0.75)
print(Q3)
iqr=Q3-Q1

lower_attendance=Q1-1.5*iqr
upper_attendance=Q3+1.5*iqr

outlier_attendeance=data[(data["attendance_percent"]<lower_attendance)|(data["attendance_percent"]>upper_attendance)]
outlier_attendeance

58.0
83.0

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status]
Index: []

In [22]:
q1=data["assignment_score"].quantile(0.25)
q3=data["assignment_score"].quantile(0.75)
iqr=q3-q1

lower_assignment=q1-1.5*iqr
upper_assignment=q3+1.5*iqr

outliers_assignment = data[(data["assignment_score"] < lower_assignment) |(data["assignment_score"] > upper_assignment)]

outliers_assignment

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
38,39,Anisha,Data Science,Itahari,20,Female,2026-01-14,134.5,10.0,Pending,70.0,-5,55,3,Manish,9856058698,user38@gmail.com,Ongoing

In [36]:
q1=data["final_score"].quantile(0.25)
q3=data["final_score"].quantile(0.75)
iqr=q3-q1

lower=q1-1.5*iqr
upper=q3+1.5*iqr

outliers_final = data[(data["final_score"] < lower) |(data["final_score"] > upper)]

outliers_final

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status]
Index: []

In [35]:
data["course_fee"] = data["course_fee"].clip(lower_fee, upper_fee)
print(data["course_fee"])
data["assignment_score"]=data["assignment_score"].clip(lower_assignment,upper_assignment)

0      134.5
1      134.5
2      134.5
3      134.5
4      134.5
       ...
345    134.5
346    134.5
347    134.5
348    134.5
349    134.5
Name: course_fee, Length: 350, dtype: float64

In [24]:
mean = data["course_fee"].mean()
std = data["course_fee"].std()

z = (data["course_fee"] - mean) / std

outliers = data[(z > 3) | (z < -3)]

outliers

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status]
Index: []

In [17]:
# Attendance Percentage
mean = data["attendance_percent"].mean()
std = data["attendance_percent"].std()
z = (data["attendance_percent"] - mean) / std
outliers_attendance = data[(z > 3) | (z < -3)]
outliers_attendance

In [25]:
# Assignment Score
mean = data["assignment_score"].mean()
std = data["assignment_score"].std()
z = (data["assignment_score"] - mean) / std
outliers_assignment = data[(z > 3) | (z < -3)]
outliers_assignment

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
38,39,Anisha,Data Science,Itahari,20,Female,2026-01-14,134.5,10.0,Pending,70.0,-5,55,3,Manish,9856058698,user38@gmail.com,Ongoing

In [7]:
# Final Score
mean = data["final_score"].mean()
std = data["final_score"].std()
z = (data["final_score"] - mean) / std
outliers_final = data[(z > 3) | (z < -3)]
outliers_final

Empty DataFrame
Columns: [student_id, student_name, course, city, age, gender, enrollment_date, course_fee, discount, payment_status, attendance_percent, assignment_score, final_score, rating, mentor, phone, email, completion_status]
Index: []